### PR TITLE
WebDriver (WDIO 5): Change isElementDisplayed to isDisplayed API call.

### LINKED ISSUE #1518: Webdriver (wdio 5) - Update the seeElement method
#### What are you trying to achieve?
Using the `I.seeElement` with Safari 12
#### What do you get instead?
Got the following error

> Provide console output if related. Use `--verbose` mode for more details.

```
The command 'GET /session/f02975f75743107ec61f41bb498de5f53bff9605/element/node-57BEB84A-0250-4B87-A857-7B82438559C9/displayed' was not found.

  Scenario Steps:

  - I.seeElement("[data-qa="addressInput"]") at Object.addressInput (test/codeceptjs/components/searchAddress.js:9:11)
  - I.clearField("[data-qa="addressInput"]") at Object.addressInput (test/codeceptjs/components/searchAddress.js:8:11)

  unknown command: The command 'GET /session/f02975f75743107ec61f41bb498de5f53bff9605/element/node-57BEB84A-0250-4B87-A857-7B82438559C9/displayed' was not found.
      at getErrorFromResponseBody (node_modules/webdriver/build/utils.js:342:10)
      at Request._callback (node_modules/webdriver/build/request.js:113:64)
      at Request.self.callback (node_modules/webdriver/node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:441:20)
      at Request.<anonymous> (node_modules/webdriver/node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:441:20)
      at IncomingMessage.<anonymous> (node_modules/webdriver/node_modules/request/request.js:1083:12)


  FAIL  | 0 passed, 1 failed   // 14s
Disconnected
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
```

### Details

* CodeceptJS version: v2.0.4
* NodeJS Version: 8+
* Operating System: MacOS Mojave
* WebDriver

### Resolutions
Update the method once this is finalised.
https://github.com/webdriverio/webdriverio/issues/2962

### PR DESCRIPTION
**Pull request by LukoyanovE**
WebDriver helper's method `seeElement`.

`browser.isElementDisplayed(elemId)` will be  deprecated.
Changed to `elem.isDisplayed()`

https://webdriver.io/docs/api/element/isDisplayed.html

#1518
This PR fix WDIO call, but there are WDIO error, due to not implemented driver's API:
https://github.com/webdriverio/webdriverio/pull/3601

### CODE REVIEW

**Comment by abjerstedt** [comment]
Just to clarify its not exactly deprecated. Its missing from the spec, and so, a few specific drivers decided to ignore it.

**Comment by DavertMik** [comment]
Failed tests!

**Comment by PeterNgTr** [comment]
Wow. That’s merged https://github.com/webdriverio/webdriverio/pull/3601

File: lib/helper/WebDriver.js [hunk 1]
```diff
@@ -1007,11 +1004,11 @@ class WebDriver extends Helper {
    * * *Appium*: supported
    */
   async dontSeeElement(locator) {
-    const res = await this._locate(locator, false);
+    const res = await this._locate(withStrictLocator(locator), true);
```
Comment (LukoyanovE) [inline lib/helper/WebDriver.js]: I enabled smartWait. In `SmartWait` tests it equals 3 sec

On test page it appears in 1 or 2 sec.
So, method finds element and fails.

**Comment by DavertMik** [comment]
Thank you!
