### PR TITLE
fix(cli): stale process

### LINKED ISSUE #4197: retryTo leads to stale process on failure
I'm sorry @kobenguyent, but we must have missed a regression with the last fix here https://github.com/codeceptjs/CodeceptJS/issues/4110

It works fine as long as assertions are a success, but as soon as there is a failure – even outside the retryTo block – the test never terminates.

Simple test code:
```js
Feature('foo');

Scenario('test issue', async ({ I }) => {
    I.amOnPage('http://example.org')
    I.waitForVisible('.nothing', 1); // should fail here but it won't terminate
    await retryTo( (tryNum) => {
        I.see(".doesNotMatter");
    }, 10);
});
```
EDIT: Adding an irregular await before the failing assertion `await I.waitForVisible('.nothing', 1)` will let the promise chain resolve.

image

### LINKED ISSUE #4211: Tests don't fail gracefully when encountering errors after test execution and stall the CI
#### What are you trying to achieve?

Test pipelines should continue gracefully when encountering an error during "after" test execution

#### What do you get instead?

When the test fails, codeceptJS fails to properly scale down the test run and keeps the browser session open, essentially turning the test thread into a zombie codeceptJS process. 

Tests running in pipelines will time out as the thread that's running these tests don't know the test has completed and that they should start the next test.

```bash
   Requesting menu-item sold-out status change to false
      I send put request "https://uri/api/v2/restaurant/1289255/category/15516284/product/487560132", {"name":"Sold Out","description":"Will be changed to sold out by automated tests","external_id":"","sort_id":4,"delivery_price":12,"pickup_price":12,"shipping_method":"pickup_delivery","sold_out":false,"image_url":null,"soft_deleted":false,"addon_set_id":null}, {"accept":"application/json","content-type":"application/json","Authorization":"Basic =="}
      › [Request] {"baseURL":"https://uri/api/v2/restaurant/1289255/category/15516284/product/487560132","method":"PUT","data":{"name":"Sold Out","description":"Will be changed to sold out by automated tests","external_id":"","sort_id":4,"delivery_price":12,"pickup_price":12,"shipping_method":"pickup_delivery","sold_out":false,"image_url":null,"soft_deleted":false,"addon_set_id":null},"headers":{"Content-Type":"application/json","Accept":"application/json","X-Session-Id":"8c7db2c0a86b","user_agent":"cw-api-automated-tests","sec-fetch-mode":"cors","access-control-allow-origin":"*","accept":"application/json","content-type":"application/json","Authorization":"Basic =="}}
      › [Response] Response error. Status code: 404
      › [Response] "404 page not found\n"
404 page not found

    [2] Error | Error: Restaurant Menu API call failed! Response: undefined
             Status: 404 (e) => { const err = (recorder.getAsyncErr() === n...
Error processing test.after event:
TypeError: Cannot read properties of undefined (reading 'ctx')
    at AllureReporter.allureTestByCodeceptTest (/Users/seth.vanwyk/workspace/project/node_modules/allure-codeceptjs/dist/index.js:89:62)
    at AllureReporter.testAfter (/Users/seth.vanwyk/workspace/project/node_modules/allure-codeceptjs/dist/index.js:159:33)
    at EventEmitter.emit (node:events:402:35)
    at Object.emit (/Users/seth.vanwyk/workspace/project/node_modules/codeceptjs/lib/event.js:149:28)
    at errHandler (/Users/seth.vanwyk/workspace/project/node_modules/codeceptjs/lib/scenario.js:116:39)
    at /Users/seth.vanwyk/workspace/project/node_modules/codeceptjs/lib/scenario.js:162:11
    at /Users/seth.vanwyk/workspace/project/node_modules/codeceptjs/lib/recorder.js:239:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    [2] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, try to save a screenshot
 › Screenshot is saving to /Users/seth.vanwyk/workspace/project/output/Desktop_-_item_is_sold_out_after_each_hook__After_for_should_remove_item_that_is_sold_out_from_basket_@site-nl_@delivery_@not-allowed-to-run-in-production_@should-remove-item-that-is-sold-out-from-basket.failed.png
  ✖ FAILED in 434ms

    [3]  Starting recording promises

-- FAILURES:

  1) Desktop - item is sold out
       should remove item that is sold out from basket @site-nl @delivery @not-allowed-to-run-in-production @should-remove-item-that-is-sold-out-from-basket:
     Error: Restaurant Menu API call failed! Response: undefined
             Status: 404
      at Object.changeMenuItemSoldOutStatus (api-calls/restaurant-menu-api.js:36:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Test.<anonymous> (/Users/seth.vanwyk/workspace/project/checkout-e2e/scenarios/multi-step-checkout/item-out-is-sold-out-alert-desktop-test.js:52:3)

  Scenario Steps:
  - I.seeElement({"xpath":"//*[@data-qa='jet-privacy-settings-button-full-consent']"}) at ./page-objects/footer/footer.js:16:41
  - I.seeElement({"xpath":"//*[@data-qa='privacy-settings-action-close']"}) at ./page-objects/footer/footer.js:15:42
  - I.say("Checking which cookie banner variant is in use") at Object.acceptCookies (./page-objects/footer/footer.js:14:7)
  - I.say("Opened page https://site/en/menu/test-restaurant-selenium?showTestRestaurants=true&utm_medium=e2e_testing&utm_source=cwplatform&utm_campaign=local&e2e=true&timestamp=1708522969025 at Wed Feb 21 2024 13:42:49 GMT+0000 (Coordinated Universal Time)") at Actor.accessURL (./steps-file.js:174:12)
  - I.grabCurrentUrl() at Actor.accessURL (./steps-file.js:173:37)
  - I.waitForInvisible({xpath: //*[contains(@data-qa,'skeleton')]}, 30) at ./steps-file.js:210:18
  - I.say("Awaiting for 30 seconds for skeleton to not be visible") at Actor.waitPageLoads (./steps-file.js:206:14)
  - I.waitForFunction(async () => {
          const state = await document.readyState;
          return state === 'interactive' || state === 'complete';
        }, 120) at Actor.waitPageLoads (./steps-file.js:197:12)
  - I.say("Awaiting for page to load with javascript") at Actor.waitPageLoads (./steps-file.js:196:12)
  - I.amOnPage("https://site/en/menu/test-restaurant-selenium?lat=53.0651908&lng=16.04760159&showTestRestaurants=true&utm_medium=e2e_testing&utm_source=cwplatform&utm_campaign=local&e2e=true&timestamp=1708522969025") at Actor.accessURL (./steps-file.js:167:14)
  - I.say("Opening the page") at Actor.accessURL (./steps-file.js:164:12)
  - I.sendGetRequest("/restaurant?slug=test-restaurant-selenium", {"X-Country-Code":"pl","Accept-Language":"en","X-Language-Code":"en"}) at getTakeawayRestaurantOpening (./api-calls/restaurant.js:6:28)

  Artifacts:
  - screenshot: /Users/seth.vanwyk/workspace/project/output/should_remove_item_that_is_sold_out_from_basket_@site-nl_@delivery_@not-allowed-to-run-in-production_@should-remove-item-that-is-sold-out-from-basket.failed.png

  2) Desktop - item is sold out
       "after each" hook: After for "should remove item that is sold out from basket @site-nl @delivery @not-allowed-to-run-in-production @should-remove-item-that-is-sold-out-from-basket":
     Error: Restaurant Menu API call failed! Response: undefined
             Status: 404
      at Object.changeMenuItemSoldOutStatus (api-calls/restaurant-menu-api.js:36:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (/Users/seth.vanwyk/workspace/project/checkout-e2e/scenarios/multi-step-checkout/item-out-is-sold-out-alert-desktop-test.js:75:3)
      at async promiseRetry.retries.retries (/Users/seth.vanwyk/workspace/project/node_modules/codeceptjs/lib/scenario.js:143:9)




  FAIL  | 0 passed, 2 failed   // 27s
```
The terminal stalls here and leaves a broken browser session open that doesn't close anymore.

> Provide test source code if related

```js
    if (response.data.message !== 'success') {
        console.log(response.data)
        throw new Error(
            `Restaurant Menu API call failed! Response: ${response.data.message}
             Status: ${response.status}`
        );
```

### Details

* CodeceptJS version: Tested on 3.5.3 and 3.5.14 
* NodeJS Version:16
* Operating System: MacOS
* puppeteer

### LINKED ISSUE #4358: [Asking for help] Process are blocking when throw error in scenario with Retry enabled
When i run to all test (~70) in 4 workers, at the end, i get stuck with this error message

```bash
✖ "after all" hook: codeceptjs.afterSuite in "Homepage feature" in 0ms
```

* CodeceptJS version: 3.6.2
* NodeJS Version: 20
* playwright: 1.43.0
* allure-codeceptjs: 2.15.1
* Configuration file:

```js

    Playwright: {
      url: testConfig.url,
      show: false,
      locale: "en-EN",
      browser: 'chromium',
      chromium: {
        args: ['--auth-server-whitelist=""'],
      },
      ignoreHTTPSErrors: true,
      fullPageScreenshots: true,
      windowSize: '1920x1080',
      waitForAction: 250,
      waitForTimeout: 10000, 
      waitForNavigation: 'load',
      restart: 'context',
      keepCookies: false,
      keepBrowserState: false
    },
```

I have allready open here https://github.com/codeceptjs/CodeceptJS/issues/3640 an issue before, but no response and the probleme has gone, but it's here again :'(

### PR DESCRIPTION
**Pull request by kobenguyent**
## Motivation/Description of the PR
- Resolves #4197
- resolves #4358 
- resolves #4211

```
  mocha:runner _addEventListener(): adding for event uncaughtException; 0 current listeners +8ms
  mocha:runner _addEventListener(): adding for event unhandledRejection; 0 current listeners +0ms
  mocha:runner run(): starting +2ms
  mocha:runner run(): emitting start +0ms

  mocha:runner run(): emitted start +1ms
  mocha:runner runSuite(): running  +0ms
  mocha:runner runSuite(): running Error 1 @error1: +1ms
Error 1 @error1 --
  mocha:runner _addEventListener(): adding for event error; 0 current listeners +1ms
    [1]  Starting recording promises
    Retries: 3
    Timeouts: 
 › [Session] Starting singleton browser session
  test issue
  mocha:runner _addEventListener(): adding for event error; 0 current listeners +1s
  mocha:runner _addEventListener(): adding for event error; 0 current listeners +1s
    I am on page "http://example.org"
    › [Browser:Error] Failed to load resource: the server responded with a status of 404 (Not Found)
    I wait for visible ".nothing", 1
    [1]  Error (Non-Terminated) | Error: element (.nothing) still not visible after 1 sec
locator.waitFor: Timeout 1000ms exceeded.
Call log:
  - waiting for locator('.nothing').first() to be visible
 | (err) => { step.status = 'failed'; step.endTime = ...
    [1] Error | Error: element (.nothing) still not visible after 1 sec
locator.waitFor: Timeout 1000ms exceeded.
Call log:
  - waiting for locator('.nothing').first() to be visible
 (e) => { const err = (recorder.getAsyncErr() === n...
    [1] <teardown>  Stopping recording promises
 › <screenshotOnFail> Test failed, try to save a screenshot
 › Screenshot is saving to /Users/t/Desktop/projects/codeceptjs-debug/output/test_issue.failed.png
  mocha:runner _addEventListener(): adding for event error; 0 current listeners +2s
    [2]  Starting recording promises
  mocha:runner _addEventListener(): adding for event error; 0 current listeners +35ms
  mocha:runner runSuite(): running Error 2 @error2: +2ms
  mocha:runner runSuite(): bailing +0ms
  mocha:runner runSuite(): running Error 3 @error3: +0ms
  mocha:runner runSuite(): bailing +0ms
  mocha:runner runSuite(): running Error 4 @error4: +0ms
  mocha:runner runSuite(): bailing +0ms
  mocha:runner runSuite(): running Working @working: +1ms
  mocha:runner runSuite(): bailing +0ms
  mocha:runner run(): root suite completed; emitting end +0ms

  OK  | 0 passed   // 4s
  mocha:runner run(): emitted end +1ms

```

From @Horsty80 

- When a throw error occurs inside promise, that stale the process, by rewrite with good reject and done call, we prevent this to happen
- Resolves #4367 

- maybe this pr can help this issue #4358

## Type of change
- [ ] :bug: Bug fix

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by kobenguyent** [comment]
ready for testing: **codeceptjs@3.6.3-beta.2**

**Review by Arhell — APPROVED** [review]

File: lib/cli.js [hunk 1]
```diff
@@ -186,20 +186,24 @@ class Cli extends Base {
...
+          err.stack = `${stack.join('\n')}\n\n${output.colors.blue(log)}`;
 
-        // clone err object so stack trace adjustments won't affect test other reports
-        test.err = err;
-        return test;
+          // clone err object so stack trace adjustments won't affect test other reports
+          test.err = err;
+          return test;
+        } catch (e) {
+          throw Error(e);
```
Comment (Horsty80) [inline lib/cli.js:205]: **question:**
@kobenguyent throwing an error are you sure about it ? i mean the issue about stale process is, i think, throw error, so maybe just log the error and return something else maybe ?

Comment (kobenguyent) [reply lib/cli.js:205]: I think we should throw an error to stop the process here.

Comment (Horsty80) [reply lib/cli.js:205]: Ok i see, so the issue isn't that this code throw an error but is that in case of error nothing is throw and the process didn't get the trigger to stop ?
Seems legit indeed :)
Thanks, i'm trying this version right now, but without retry so i didn't confirm that modif is working

Comment (kobenguyent) [reply lib/cli.js:205]: I tried the patch using the example here. https://github.com/codeceptjs/CodeceptJS/issues/4197 looking good so far.

**Comment by kobenguyent** [comment]
ready for testing: codeceptjs@3.6.3-beta.3

**Review by DavertMik — APPROVED** [review]
Good work!
Looks good to me. Seems like a valid solution
