### PR TITLE
fix: skip Runner to detect MetaStep

### LINKED ISSUE #1763: Node version 12 support
#### What are you trying to achieve?
Run tests on node v12.6.0

#### What do you get instead?
Extra text (`Runner: runTest`) from `stdout`.
It works fine in Node v10.16.0

> Provide console output if related. Use `--verbose` mode for more details.

```bash
  4) CodeceptJS session
       should run with 3 sessions:

      check steps execution order
      + expected - actual

       [
      -  "Runner: runTest "
         "I do \"writing\""
         "davert: I do \"reading\""
      -  "Runner: runTest "
         "I do \"playing\""
         "john: I do \"crying\""
         "davert: I do \"smiling\""
      -  "Runner: runTest "
         "I do \"laughing\""
         "mike: I do \"spying\""
         "john: I do \"lying\""
      -  "Runner: runTest "
         "I do \"waving\""
       ]
      
      at test/runner/session_test.js:24:19                                                                                                                                                      
      at ChildProcess.exithandler (child_process.js:288:7)                                                                                                                                      
      at maybeClose (internal/child_process.js:1021:16)                                                                                                                                         
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)                                                                                                                  

```

> Provide test source code if related
[`session_test.js:16`](https://github.com/Codeception/CodeceptJS/blob/38e04f564cbb3e954dc591636c9d2f26a3f8c920/test/runner/session_test.js#L16)

```js

  it('should run with 3 sessions', (done) => {
    exec(`${codecept_run} --steps --grep "@1"`, (err, stdout, stderr) => {
      const lines = stdout.match(/\S.+/g);

      const list = grepLines(lines, 'basic session @1');
      list.pop();
      testStatus = list.pop();
      testStatus.should.include('OK');
      list.should.eql([
        'I do "writing"',
        'davert: I do "reading"',
        'I do "playing"',
        'john: I do "crying"',
        'davert: I do "smiling"',
        'I do "laughing"',
        'mike: I do "spying"',
        'john: I do "lying"',
        'I do "waving"',
      ], 'check steps execution order');
      done();
    });
  });
```

### Details

* CodeceptJS version: 2.2.0
* NodeJS Version: 12.6.0
* Operating System: Linux

### PR DESCRIPTION
**Pull request by VikalpP**
resolves #1763

### CODE REVIEW

File: lib/step.js [hunk 1]
```diff
@@ -154,8 +154,11 @@ function detectMetaStep(stack) {
     if (isTest(line) || isBDD(line)) break;
     const fnName = line.match(/^at (\w+)\.(\w+)\s\(/);
     if (!fnName) continue;
-    if (fnName[1] === 'Generator') return; // don't track meta steps inside generators
-    if (fnName[1] === 'recorder') return; // don't track meta steps inside generators
+    if (fnName[1] === 'Generator'
+      || fnName[1] === 'recorder'
+      || fnName[1] === 'Runner'
```
Comment (VikalpP) [inline lib/step.js]: Instead of patching things like this, can you explain to me what is the only needed part?
So I can refactor to better code.

while debugging, I didn't find the exact case for detecting meta-step.

**Comment by DavertMik** [comment]
Thanks. Could you also update travis.yml and replace node version 10 with 12 so we could try this fix.

**Comment by VikalpP** [comment]
Don't you think that we should also test for node 10?🤔

**Comment by VikalpP** [comment]
@DavertMik Should I replace with Node 10 or add Node 12 into CI?

**Comment by DavertMik** [comment]
>  Should I replace with Node 10 or add Node 12 into CI?

I will do it. Thanks!
