### PR TITLE
fix(3367): Android Click Broken When Platform Definition Capitalized

### LINKED ISSUE #3367: Android Click Broken When Platform Definition Capitalized
I recently attempted to set up codceptjs for Android automation using the desired capabilities defined on this page (https://codecept.io/mobile/#configuring). The example capabilities are defined like this:

`helpers: {
  Appium: {
    app: "my_app.apk",
    platform: "Android",
    desiredCapabilities: {}
  }
}`

Using these capabilities, every call to I.click() would fail with a 404 error coming back from Appium. After some investigation, I found this line in [WebDriver.js](https://github.com/codeceptjs/CodeceptJS/blob/e956cb8580764f07facf7c07a315775192eee03e/lib/helper/WebDriver.js)

` const clickMethod = this.browser.isMobile && this.browser.capabilities.platformName !== 'android' ? 'touchClick' : 'elementClick';`

I validated that when I pass in a platform of "**Android**", the touch API is called and seems to be incompatible with Android automation. However, if I lower case the platform to "**android**", then the element click method is used and the automation executes properly.

Given this, the best solution would be to make this check case insensitive. If that is not possible, then the documentation (and possibly code generation) needs to be updated to reflect the case sensitive nature of this code.

### PR DESCRIPTION
**Pull request by kobenguyent**
## Motivation/Description of the PR
- Resolves #3367 

Applicable helpers:
- [x] WebDriver
- [x] Appium

## Type of change
- [x] :bug: Bug fix

## Checklist:
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

File: lib/helper/WebDriver.js [hunk 1]
```diff
@@ -567,6 +567,9 @@ class WebDriver extends Helper {
       });
     }
 
+    if (this.browser.capabilities && this.browser.capabilities.platformName) {
+      this.browser.capabilities.platformName = this.browser.capabilities.platformName.lowercase();
```
Comment (DavertMik) [inline lib/helper/WebDriver.js]:
```suggestion
      this.browser.capabilities.platformName = this.browser.capabilities.platformName.lowercase();
```
maybe it should be https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase ?

**Review by DavertMik — CHANGES_REQUESTED** [review]

File: lib/helper/WebDriver.js (hunk 1 above)
Comment (kobenguyent) [reply lib/helper/WebDriver.js]: Sorry, my bad! Updated.

**Comment by DavertMik** [comment]
Thanks!
