### PR TITLE
fix(appium): type of setNetworkConnection()

### LINKED ISSUE #3993: Appium: Missing parameter definition in "setNetworkConnection"
TypeScript test:

image

### Details

* CodeceptJS version: 3.5.7
* NodeJS Version: 18.15
* Operating System: Ubuntu 23.10
* Appium 2.2.1

### PR DESCRIPTION
**Pull request by mirao**
## Motivation/Description of the PR
- Resolves #3993 .

Applicable helpers:

- [ ] Playwright
- [ ] Puppeteer
- [ ] WebDriver
- [ ] REST
- [ ] FileHelper
- [x] Appium
- [ ] TestCafe

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] stepTimeout
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [x] :bug: Bug fix
- [x] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [x] Tests have been added
- [x] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

File: lib/helper/Appium.js [hunk 1]
```diff
@@ -921,11 +921,12 @@ class Appium extends Webdriver {
...
    * ```
-   * See corresponding [webdriverio reference](http://webdriver.io/api/mobile/setNetworkConnection.html).
-   *
-   * @return {Promise<{}>}
+   * See corresponding [webdriverio reference](https://webdriver.io/docs/api/chromium/#setnetworkconnection).
    *
    * Appium: support only Android
+   *
+   * @param {number} value The network connection mode bitmask
+   * @return {Promise<{}>}
```
Comment (kobenguyent) [inline lib/helper/Appium.js]: Do we actually return anything here or just void? 🤔

Comment (mirao) [reply lib/helper/Appium.js]: Fixed. My testing says that it returns a number. Also a docs confirms it: https://webdriver.io/docs/api/chromium/#setnetworkconnection

**Review by kobenguyent — APPROVED** [review]

**Review by Arhell — APPROVED** [review]
