### PR TITLE
fix: mock server for internal tests

### LINKED ISSUE #5237: create a simple REST server for internal tests
Currently we are using https://reqres.in/api/ third party for some internal tests.

- Create a simple REST server so that we could use for such kinds of tests.
- Decouple with third party API server
- Control more what we want to test
- Update every test where using the third party API

### PR DESCRIPTION
**Pull request by kobenguyent**
## Motivation/Description of the PR
- Description of this PR, which problem it solves
- Resolves #5237 

Applicable helpers:

- [ ] Playwright
- [ ] Puppeteer
- [ ] WebDriver
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] TestCafe

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] stepTimeout
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [ ] 🧹 Chore
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

File: test/acceptance/config_test.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ Scenario('change config 5 @WebDriverIO @Puppeteer @Playwright', ({ I }) => {
 
 Scenario('make API call and check response @Playwright', ({ I }) => {
   I.amOnPage('/')
-  I.makeApiRequest('get', 'https://reqres.in/api/users?page=2', { headers: {'x-api-key': 'reqres-free-v1'}})
+    I.makeApiRequest('get', 'http://localhost:3001/api/users?page=2', { headers: {'x-api-key': 'reqres-free-v1'}})
```
Comment (thomashohn) [inline test/acceptance/config_test.js]: Fix formatting

File: test/data/app/view/form/fetch_call.php [hunk 2]
```diff
@@ -53,7 +53,7 @@
     const getPostData = () =>
       getData("https://jsonplaceholder.typicode.com/posts/1");
     const getCommentsData = () =>
-      getData("https://reqres.in/api/comments/1");
+  getData("http://localhost:3001/api/comments/1");
```
Comment (thomashohn) [inline test/data/app/view/form/fetch_call.php]: Fix formatting

File: test/helper/Playwright_test.js [hunk 3]
```diff
@@ -1041,9 +1041,9 @@ describe('Playwright', function () {
 
   describe('#makeApiRequest', () => {
     it('should make 3rd party API request', async () => {
-      const response = await I.makeApiRequest('get', 'https://reqres.in/api/users?page=2')
-      expect(response.status()).to.equal(200)
-      expect(await response.json()).to.include.keys(['page'])
+  const response = await I.makeApiRequest('get', 'http://localhost:3001/api/users?page=2')
```
Comment (thomashohn) [inline test/helper/Playwright_test.js]: formatting should be fixed

File: test/helper/Playwright_test.js [hunk 4]
```diff
@@ -1054,10 +1054,10 @@ describe('Playwright', function () {
     it('should convert to axios response with onResponse hook', async () => {
       let response
       I.config.onResponse = resp => (response = resp)
-      await I.makeApiRequest('get', 'https://reqres.in/api/users?page=2')
-      expect(response).to.be.ok
-      expect(response.status).to.equal(200)
-      expect(response.data).to.include.keys(['page', 'total'])
+  await I.makeApiRequest('get', 'http://localhost:3001/api/users?page=2')
```
Comment (thomashohn) [inline test/helper/Playwright_test.js]: formatting should be fixed

**Review by thomashohn — APPROVED** [review]
