### PR TITLE
fix(3370): els[0]._scrollIntoViewIfNeeded is broken with pupputeer > 14.4.0

### LINKED ISSUE #3370: els[0]._scrollIntoViewIfNeeded while upgrading Puppeteer version from 10.2.0 to 15.4.0
#### What are you trying to achieve?

Upgrade Puppeteer version from 10.2.0 to 15.4.0

#### What do you get instead?

TypeError: els[0]._scrollIntoViewIfNeeded is not a function

> Provide console output if related. Use `--verbose` mode for more details.

TypeError: els[0]._scrollIntoViewIfNeeded is not a function
    at PuppeteerHelper.scrollTo (..\node_modules\codeceptjs\lib\helper\Puppeteer.js:752:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PuppeteerHelper.scrollToElement 

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.3.4
* NodeJS Version: 14
* Operating System: Windows
* puppeteer || webdriverio || testcafe version (if related) : Puppeteer version : 15.4.0
* Configuration file: package.json

  "dependencies": {
        "codeceptjs": "^3.3.4",
        <project related dependencies>
    },
    "devDependencies": {
        "puppeteer": "^15.4.0",
        <project related dependencies>
    }

```js
# paste config here
```

### PR DESCRIPTION
**Pull request by kobenguyent**
## Motivation/Description of the PR
- Resolves #3370 

Applicable helpers:
- [x] Puppeteer

## Type of change
- [x] :bug: Bug fix

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

File: lib/helper/Puppeteer.js [hunk 1]
```diff
@@ -749,7 +749,8 @@ class Puppeteer extends Helper {
     if (locator) {
       const els = await this._locate(locator);
       assertElementExists(els, locator, 'Element');
-      await els[0]._scrollIntoViewIfNeeded();
```
Comment (DavertMik) [inline lib/helper/Puppeteer.js:752]: how about doing try-catch or checking for this method to support Puppeteer <= 14 ?

**Review by DavertMik — CHANGES_REQUESTED** [review]

File: lib/helper/Puppeteer.js (hunk 1 above)
Comment (kobenguyent) [reply lib/helper/Puppeteer.js:752]: I guess with new change `await el.evaluate((el) => el.scrollIntoView());` that is backward compatibility.
