### PR TITLE
(fix): ambiguous description on puppeteer helper

### LINKED ISSUE #2065: Confusing description
https://github.com/Codeception/CodeceptJS/blob/fcb0c8ba1c3c234c8d8e1506f4f4dbe5acad5a18/lib/helper/Puppeteer.js#L2118

Now this shows 

```
     Element "context element" was not found by text|CSS|XPath

```

### PR DESCRIPTION
**Pull request by PeterNgTr**
## Motivation/Description of the PR

Applicable helpers:

- [ ] Webdriver
- [x] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe

- Description of this PR, which problem it solves
Fixes #2065 

**Before**
`Element "context element" was not found by text|CSS|XPath`

**After**
`Element ".//*[@data-qa='carrier-bag-charge-label']" was not found by text|CSS|XPath`

## Type of change

- [ ] Breaking changes
- [ ] New functionality
- [x] Bug fix
- [ ] Documentation changes/updates
- [ ] Hot fix
- [ ] Markdown files fix - not related to source code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

File: lib/helper/Puppeteer.js [hunk 1]
```diff
@@ -2147,7 +2147,7 @@ async function proceedSee(assertType, text, context, strict = false) {
     const locator = new Locator(context, 'css');
     description = `element ${locator.toString()}`;
     const els = await this._locate(locator);
-    assertElementExists(els, 'context element');
+    assertElementExists(els, locator.output);
```
Comment (Vorobeyko) [inline lib/helper/Puppeteer.js]: I suggest you use a `locator.toString ()`

Because in the locator.js the method `toString` converts the locator via output:
https://github.com/Codeception/CodeceptJS/blob/master/lib/locator.js#L76

**Comment by DavertMik** [comment]
Thank you!
