### PR TITLE
Add mocha before hook issue fix

### LINKED ISSUE #2349: Gherkin, feature file - an error in "background" completely terminates the process for the entire file.
#### What are you trying to achieve?
Run all scenarios within one feature file with a background.

#### What do you get instead?
Only part of the scenarios is run.

### Steps to reproduce
Create one feature file - the file consists of:
1.Background;
2.Several scenarios;
3.Combine these scripts with a single tag.

Be sure to have failed in the background. Run the script using --grep.
The error is that as soon as the first scenario starts and it falls in the background, the process automatically ends and all remaining scenarios will not be launched.

* CodeceptJS version: 2.6.1
* NodeJS Version: 12
* Operating System: macOS
* webdriverio + gherkin

### PR DESCRIPTION
**Pull request by koushikmohan1996**
# Description
If a test is failed in `before` , the rest of the tests are not executed and the status of the test is also not reported.

Hereafter these tests are marked as skipped and a new event `test.skipped` will be triggered

## Before
before

## After
after

Fixes #2349

### CODE REVIEW

File: lib/reporter/cli.js [hunk 1]
```diff
@@ -42,6 +44,9 @@ class Cli extends Base {
     });
 
     runner.on('fail', (test, err) => {
+      if (test.ctx.currentTest) {
+        this.failedSteps.push(test.ctx.currentTest.id);
```
Comment (DavertMik) [inline lib/reporter/cli.js:48]: why it is called failedSteps when you add a test id into it?

File: lib/reporter/cli.js [hunk 2]
```diff
@@ -90,6 +95,23 @@ class Cli extends Base {
       });
     }
 
+    runner.on('suite end', suite => {
+      let skippedCount = 0;
+      const grep = require('../container').mocha().options.grep;
```
Comment (DavertMik) [inline lib/reporter/cli.js:100]: I think you can get mocha options from runner here.
I would not recommend use circular reference like this: mocha -> cli -> container -> mocha

**Comment by Vorobeyko** [comment]
what issue it fix?

**Comment by koushikmohan1996** [comment]
> what issue it fix?

@Vorobeyko Linked the issue now, fix is not complete. Will add complete description once it is fixed completely

**Comment by mirao** [comment]
It seems that skipped scenario is logged incorrectly twice in CodeceptJS 2.6.2:

2.6.2 :beetle: :
```bash
$ npx codeceptjs run
CodeceptJS v2.6.2
Using test root "/home/mirao/workspace/codeceptjs/tests/demo"

Login --
  S Successful login
  S Failed login
  S Successful login
  S Failed login

  OK  | 0 passed, 4 skipped   // 3ms
```
2.6.1 :heavy_check_mark: :
```bash
$ npx codeceptjs run
CodeceptJS v2.6.1
Using test root "/home/mirao/workspace/codeceptjs/tests/demo"

Login --
  S Successful login
  S Failed login

  OK  | 0 passed, 2 skipped   // 3ms
```

**Comment by koushikmohan1996** [comment]
@mirao Can you share with me the sample test case? Github repo will also do!

**Comment by mirao** [comment]
E.g. this one:
```js
Feature("Login");

Scenario.skip("Open a page", (I) => {
    I.amOnPage("/");
});
```
log:
```bash
$ npx codeceptjs run
CodeceptJS v2.6.2
Using test root "/home/mirao/workspace/codeceptjs/tests/demo"

Login --
  S Open a page
  S Open a page

  OK  | 0 passed, 2 skipped   // 3ms
```

**Comment by koushikmohan1996** [comment]
Thanks, Let me check

**Comment by koushikmohan1996** [comment]
@mirao Found the issue, Will fix it right away
