### PR TITLE
fix: Avoid failiure report on successful retry in worker

### LINKED ISSUE #1985: Feature Level Retires not being correctly reported with run-workers
#### What are you trying to achieve?
We have some flaky tests that we use the retry function in CodeceptJS for, and it looks like when we run the tests with run-workers and a test fails, but then passes on the retry, the failure is reported and the test fun fails completely.

#### What do you get instead?
When a retry is executed and subsequently passes, the run should succeed 

### Details

* CodeceptJS version: 2.3.3
* NodeJS Version:v12.4.0
* Operating System:Alpine Linux
* WebDriverIO: 5.15.1

### PR DESCRIPTION
**Pull request by koushikmohan1996**
## Motivation/Description of the PR
Tests are not reported as passed if the test is passed in a retry while using run-workers.

While appending test status, passing of already failed test is not accounted for. So adding a map with `test.id` and appending status accordingly fixes the issue.

- Fixes #1985 

## Type of change

- [ ] Breaking changes
- [ ] New functionality
- [X] Bug fix
- [ ] Documentation changes/updates
- [ ] Hot fix
- [ ] Markdown files fix - not related to source code

## Checklist:

- [X] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- test/data/sandbox/workers/retry_test.workers.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DavertMik/CodeceptJS/pullRequest?prid=4831010&bid=16050387)

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- test/data/sandbox/workers/retry_test.workers.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DavertMik/CodeceptJS/pullRequest?prid=4831010&bid=16050387)

File: lib/command/run-workers.js [hunk 1]
```diff
@@ -209,3 +214,12 @@ function simplifyObject(object) {
       return obj;
     }, {});
 }
+
+const updateFinishedTests = (test) => {
+  const { id } = test;
+  if (finishedTests[id]) {
+    const stats = { passes: 0, failures: -1, tests: 0 };
```
Comment (PeterNgTr) [inline lib/command/run-workers.js]: could you enlighten me why `failures: -1` 😅

Comment (koushikmohan1996) [reply lib/command/run-workers.js]: @PeterNgTr if `finishedTests` already have that particular id, it means that the test is updated again. Now there are 2 possibilities it may be passed or failed which is updated in the event.
So for both cases, failure should be decremented

**Comment by DavertMik** [comment]
@koushikmohan1996 is that compatible with your PR with the refactoring of workers?

**Comment by DavertMik** [comment]
Thank you!
